name: "docker build"
on:
  push:
    branches:
      - make

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & Push Docker Image
        run: |
          docker build . \
            -t aniskhan001/kubectl-helm:make \
            -t aniskhan001/kubectl-helm:make-${HELM_VERSION} \
            --build-arg K8S_VERSION=v${K8S_VERSION} \
            --build-arg HELM_VERSION=v${HELM_VERSION}
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push aniskhan001/kubectl-helm
        env:
          K8S_VERSION: 1.18.6
          HELM_VERSION: 3.2.4

  update_dockerhub_description:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Hub Description Update
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERHUB_REPOSITORY: aniskhan001/kubectl-helm
