name: "Docker push"
on:
- push

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - name: Sign-in to Docker
      uses: actions/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.GITHUB_DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_DOCKER_PASSWORD }}
